### ISSUE TITLE
文件版號

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#113]
![2019-6-27 下午 01-52-55](https://user-images.githubusercontent.com/9152238/60240359-45597700-98e3-11e9-8af5-d0554ec92697.png)

**Comment by zxc37880** [comment]
commit: [cc764c9] 修改完成。

**Comment by chanchengliang** [comment]
將所有按鈕上的版號移除，只留一個地方顯示。
