### ISSUE TITLE
誤觸發：「欄位是必要項」的訊息

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#117]
若選擇下面四個項目，原有填寫的欄位會被觸發「欄位是必要項」的訊息。
![1](https://user-images.githubusercontent.com/9152238/60475429-dba5e800-9ca9-11e9-9ffc-56e3f036f05e.png)

**Comment by zxc37880** [comment]
Commit: [0705831]，已修正完成。
