### ISSUE TITLE
工單新增欄位

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#119]
建議在RD／FD／QA等各單位工作項目外，再增加一個可以記述整體需求（背景，說明等）的欄位

註：
他們的意思是->專案描述

**Comment by zxc37880** [comment]
Commit: [96be151]，以修改。

**Comment by chanchengliang** [comment]
![333](https://user-images.githubusercontent.com/9152238/61197998-40316000-a70a-11e9-892a-bb271fe0b62f.png)
請把該欄，移到如圖片的位置。

**Comment by zxc37880** [comment]
Commit: [7013c28]，以修改。
