### ISSUE TITLE
搜尋頁-報表，樣式如附件。

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#130]
[複本 yao20190625.xlsx](https://github.com/chanchengliang/FontWorkOrder/files/3385071/yao20190625.xlsx)

**Comment by Le1779** [comment]
已新增

**Comment by chanchengliang** [comment]
可以照搜尋修件即可，不要全部的結果都在excel表中。

**Comment by Le1779** [comment]
已調整

**Comment by chanchengliang** [comment]
請增加附圖20200423.png中4項內容
1．PM欄加：“申請日期”～“預定完成日”
2．沒有需求的部門加：n/a
3．FD／RD／QA欄加：～各“部門預計完成日”
4．Delay部門請用紅色標示
![20200423](https://user-images.githubusercontent.com/9152238/80062046-63c0eb00-8565-11ea-8c2a-42b8c1f455c7.png)

**Comment by Le1779** [comment]
已調整
