### ISSUE TITLE
搜尋頁-「結案/未結案」，元件高度不一致，且字被遮住了

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#131]
![2](https://user-images.githubusercontent.com/9152238/61115337-d411ea80-a4c4-11e9-9ee4-a9065279d881.png)

**Comment by zxc37880** [comment]
重新整理清除catch或開啟無痕顯示後可解決。

**Comment by chanchengliang** [comment]
沒解決

**Comment by zxc37880** [comment]
前端顯示方式因 #178 需求修改顯示，因此把原本顯示的下拉選單改為是否結案按鈕。

**Comment by chanchengliang** [comment]
請把「結案未結案」的部份移至「產出格式」的位置，原搜尋「產出格式」的欄位拿掉。
![2019-11-28 下午 12-06-46](https://user-images.githubusercontent.com/9152238/69776865-e2914200-11d8-11ea-9de6-0b78625ef684.png)

**Comment by ponyhsu** [comment]
已修正
