### ISSUE TITLE
任何的通知mail附上專案的超連結

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#141]
超連結網址組成方法：
http://192.168.255.17:8088/Encrypt/[Encrypt String]

[Encrypt]的內容：
([UserID_Password_AppinsttanceID])取base64後，再進行左右交換。
例如：
ABCDEFGH->BADCFEHG
當使用者直接按下超連結後，會自動登入，驗證無誤後，會自動跳轉到該專案的詳情頁。

**Comment by zxc37880** [comment]
Commit:  [de8707b]，建立工單與進行中修改工單會寄信通知並傳送連結。
