### ISSUE TITLE
下載檔案多選的功能

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#144]
RD 常會在不同路徑下，選擇下載的檔案，但切換到別的路徑時，前面的選項就會消失。
是否可以記住？
![pic](https://user-images.githubusercontent.com/9152238/62181587-597f1100-b386-11e9-8121-fde54eb88369.png)

**Comment by Le1779** [comment]
分開下載會不方便嗎? 好像沒用過有這種功能的產品
