### ISSUE TITLE
NAS Path 新需求，如附件

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#173]
[NasPath.docx](https://github.com/chanchengliang/FontWorkOrder/files/3594209/NasPath.docx)

**Comment by Le1779** [comment]
第2、3項已完成

**Comment by zxc37880** [comment]
第1項UI完成。

**Comment by chanchengliang** [comment]
頁面上多增加一個選項：
往上建立 [1]層目錄
\\a\b\c
目前自動會建立c，但使用者若填[3], 則會建立到\\a

**Comment by chanchengliang** [comment]
![2020-4-7 下午 05-38-49](https://user-images.githubusercontent.com/9152238/78654377-0129e700-78f7-11ea-8b77-69435ea75ce8.png)

**Comment by chanchengliang** [comment]
更新需求：\\a\b\c
若使用者填 231的話，則會依據\b\c\1建立目錄

**Comment by chanchengliang** [comment]
已完成
