### ISSUE TITLE
請在已完成的搜尋介面加上部門別

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#175]

**Comment by Le1779** [comment]
已新增 [bbffbdc](http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/bbffbdc27bee271feb17cea52871ab68529b7950)

**Comment by Le1779** [comment]
已修改 [57de1b6](http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/57de1b665702aada03ee307cba2fda98d74becd7)

**Comment by chanchengliang** [comment]
![2019-10-14 上午 11-38-44](https://user-images.githubusercontent.com/9152238/66728393-36d5a200-ee77-11e9-8ff2-5bdb0a3e7348.png)

搜尋出來的結果不在處理時間的範圍內

**Comment by Le1779** [comment]
![截圖 2019-10-14 上午11 58 33](https://user-images.githubusercontent.com/28716003/66728857-1a873480-ee7a-11e9-8334-1fb4a2d8a165.png)
搜尋10/14~10/31的結果
