### ISSUE TITLE
「進行中」的功能可能有問題

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#183]
Kevin:
WO-20190918-2FE5
WO-20180327-990A

Boren:
WO-20190412-A29D
WO-20190523-EEE9

Pony:
WO-20190628-3755
WO-20190628-AE64

以上是我認為有問題的案件，雖然進行中有列名，但是可能個人的待處理卻沒有，麻煩請在工單系統上確認一下。
另，再請用此修正過後的查一下是不是可以排除此BUG(使用SQL  Management Studio：

SELECT * FROM(
SELECT DENSE_RANK() OVER(ORDER BY AppInstanceID) AS ROWNUM, * from vwWfActivityInstanceTasks
    WHERE
     1 = 1
     AND ProcessState != 7
     AND (ActivityType = 4 OR WorkItemType = 1)
     AND TaskState <> 32
     AND EndedByUserID IS NULL
     AND ProcessGUID = '6546302d-fe9b-4b48-9596-1ca64114851d') 
     as v1 where ActivityState <>4  ORDER BY v1.ROWNUM

**Comment by Le1779** [comment]
WO-20190918-2FE5 有排除
WO-20180327-990A 這張已經結案了

**Comment by ponyhsu** [comment]
WO-20190628-3755 有正確列於待處理人員-葛幼寧的待處理清單中
WO-20190628-AE64 有排除此bug

**Comment by zxc37880** [comment]
WO-20190412-A29D
WO-20190523-EEE9
兩張都已經結案了，在進行中沒出現。

**Comment by chanchengliang** [comment]
案號：7404-新標楷
案號：2353-新標宋
此兩案仍然有問題

**Comment by chanchengliang** [comment]
![4](https://user-images.githubusercontent.com/9152238/70037345-64c2a180-15f1-11ea-9294-32c0d7ffa379.png)

藍色及紅色被分配到的案件麻煩驗證一下。
藍色的案件的被指派人應該是正確的。
紅色的案件的被指派人應該是錯誤的。

**Comment by Le1779** [comment]
已驗證 無誤

**Comment by ponyhsu** [comment]
已驗證 無誤

**Comment by zxc37880** [comment]
F9C6  看不出來有沒有錯誤，上面下面都有出現，剛好都是同一個人。
