### ISSUE TITLE
download_temp

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#185]
WO-20191107-E7F9工單下載最新檔案的Retail目錄中有一個奇怪的download_temp應該要被系統自動砍掉的，但沒砍掉。
![2019-11-20 下午 01-42-50](https://user-images.githubusercontent.com/9152238/69212386-1b5b6680-0b9c-11ea-97f0-491292c4ea57.png)

**Comment by chanchengliang** [comment]
這個問題協理又提出來一次了，請確認如何解決？

**Comment by Le1779** [comment]
已修正，改為隱藏"_download_temp"的資料夾
