### ISSUE TITLE
待處理頁面：預定完成日，請加上排序的功能

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#187]
![2019-11-28 下午 12-06-46](https://user-images.githubusercontent.com/9152238/69776562-be813100-11d7-11ea-805c-cf35e6e3e3cc.png)

**Comment by zxc37880** [comment]
後台已排序預定完成日由小到大

**Comment by chanchengliang** [comment]
功能不work。(請以明芬登入正式站)
另，此功能為前端需要加上一個上下箭頭讓使用者可以選擇排序的方式
