### ISSUE TITLE
調整Flow流程

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#189]
各部門的RD/FD不需要丟案子給QA時，再經過PM(系統只需要發email通知即可)
1．需要修改流程圖
2．PM頁面需要更動

**Comment by chanchengliang** [comment]
![2019-12-3 下午 01-48-09](https://user-images.githubusercontent.com/9152238/70023929-d855b600-15d3-11ea-90ba-7657008c826b.png)

IsApprove這個值在只有在單子給QA部門時，才能設成True. (且IsQAPass=False)

**Comment by chanchengliang** [comment]
流程圖已完成修改，請更改UI，謝謝。

**Comment by chanchengliang** [comment]
![2019-12-3 下午 01-48-09](https://user-images.githubusercontent.com/9152238/70025285-8e6ecf00-15d7-11ea-867d-75ada2272251.png)

若要給QA部門的話，就IsQAPass = false, 其它都照舊。

**Comment by zxc37880** [comment]
前端已更新推上git

**Comment by chanchengliang** [comment]
重新修改後上測試站。
