### ISSUE TITLE
PM更新檔案內容，但下載最新檔案時，卻還是舊版的檔案

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#192]
WO-20191128-07AA
下載PM 2019/11/29 13:47 更新上傳的Excel檔，但打開檔案仍是11/28的檔案內容。
到查看上傳紀錄裡下載檔案，卻是有更新過的Excel檔。

請下載的檔案請求加上 ?v=時間(timetick)
例如：
http://XXXXX/work.xls?v=1234555555

參考資料：
https://medium.com/frochu/http-caching-3382037ab06f

**Comment by zxc37880** [comment]
#192 下載檔案加上時間戳記
[4d96116](http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/4d961163b0cb20d14a7d705d65499f8ca8eb62ee)
