### ISSUE TITLE
在下載最新檔案的地方，新增可以剪下及貼上的功能

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#193]
在下載最新檔案的地方，新增可以剪下及貼上的功能，方便整理最新檔案。

此問題可先看google drive的做法，評估可不可行，再行製作。

![下載最新檔案新增可以剪下及貼上功能](https://user-images.githubusercontent.com/9152238/71236421-e4fb3d80-2339-11ea-9c93-9a8e19624b9f.png)

**Comment by Le1779** [comment]
已完成
