### ISSUE TITLE
待處理案件處理完後, 待處理案件數量不會減少

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#194]
請連絡AlanWang操作過程。

RenewTaskCount() <-----此函式會更新三個數目(待辦，進行中，已完成)

**Comment by zxc37880** [comment]
以修改. [431a5f0](http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/431a5f01abf496310b4587445f02af598f630c92)

**Comment by chanchengliang** [comment]
請停留在待處理頁面

**Comment by chanchengliang** [comment]
請於2/21解決

**Comment by zxc37880** [comment]
測試站已修正。
