### ISSUE TITLE
PM收到退回時的工單

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#198]
目前有「送出」「退回(Franz)」

看來「送出」和「退回」在PM的狀況下，此兩按鈕為同樣的用功能。(在更改為新流程之後)

但，若是Franz在「退回」的理由寫的是：請將此單先給RD
則此單陷入無法處理的狀況。

建議：
PM收到退回單時，畫面原來建單時的相同即可。

**Comment by zxc37880** [comment]
可能因修改流程問題造成此情況，已修正。
