### ISSUE TITLE
需求變更：當使用者勾選不上傳NAS檔案時

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#199]
當使用者勾選不上傳NAS檔案時，目錄會自動產生一個檔名「字型資料如工單所描述」的檔案，
請把此檔改成「NAS路徑的名稱」

**Comment by chanchengliang** [comment]
先試著改改看。
但 \\a\b\c
可能是特殊字元

**Comment by Le1779** [comment]
已調整
用"＼"代替原本的路徑符號，用"｜"來分割兩筆nas路徑
