### ISSUE TITLE
新功能：log，可嵌入多個影像檔案

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#202]
前端：請比照github的作法或是其它知名的網站的作法。
github藉由拖曳的方式，拖入input text後，會變成超連結的url

後台：
新建一個目錄LogAttachedFiles
把相關的後台目錄客戶上傳的檔案放在此。

![17](https://user-images.githubusercontent.com/9152238/74618463-ddef8080-516c-11ea-92ed-2f959617863c.png)

有問題我們討論一下

**Comment by Le1779** [comment]
已調整

**Comment by chanchengliang** [comment]
email發出來的內容沒有顯示出圖片。
