### ISSUE TITLE
新需求：NAS Path需能修改(刪除)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#203]
![9](https://user-images.githubusercontent.com/9152238/74619632-2610a200-5171-11ea-87d8-436700548ea4.png)

**Comment by zxc37880** [comment]
http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/df1711bdb9f9d4c01833a26efc4bc0f2bd09faaa

**Comment by zxc37880** [comment]
功能已完成。[http://10.0.0.54:8088/Repository/FontWorkOrder/master/Commit/df1711bdb9f9d4c01833a26efc4bc0f2bd09faaa](連結)

**Comment by chanchengliang** [comment]
請照下列需求修改第二版：
![image](https://user-images.githubusercontent.com/9152238/75737973-fdc19f80-5d3b-11ea-9614-2baa24b47b6d.png)

**Comment by chanchengliang** [comment]
UI請進行調整。
比對的部份程式碼提示如下:
bool flag = false;
for (int i = 0; i < naspath1.Length; i++)
{
      if (naspath1[i] != naspath2[i])
      {
          newNaspath = <Font Red> + naspath1[i];
          flag =true;
       }

      if (naspath1[i] == naspath2[i] && flag == true)
    {
          newNaspath =naspath1[i] + </Font Red>
          flag =false;
    }
}
![1](https://user-images.githubusercontent.com/9152238/76481901-a7e0ac00-644d-11ea-8ead-baffd22d0755.png)

**Comment by chanchengliang** [comment]
但因為刪除就沒了。所以刪除的動作要記錄下(誰刪除)，刪除了什麼(NAS Path). 
例： "Taylor刪除了\\nasfd2\log這個Naspah記錄"
另，自己只能修改(刪除)自己部門的NAS Path記錄，不能刪別部門的。

**Comment by zxc37880** [comment]
已完成(git上測試站)。

**Comment by chanchengliang** [comment]
比較的部份有bug，Taylor反應：
![1](https://user-images.githubusercontent.com/9152238/77869624-c1695c80-7271-11ea-9874-42032512a84c.jpg)
![2](https://user-images.githubusercontent.com/9152238/77869628-c3cbb680-7271-11ea-9362-123e6f410005.jpg)

**Comment by chanchengliang** [comment]
另外，需要考慮到多個NAS Path的問題。

**Comment by zxc37880** [comment]
測試站已修改功能。
