### ISSUE TITLE
功能修正：當使用者log留下image的留言時，mail中無法顯示圖片

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#205]
Pony若有問題，可以請教Kevin

**Comment by ponyhsu** [comment]
已修正，並已推上

**Comment by chanchengliang** [comment]
![messageImage_1583212077150](https://user-images.githubusercontent.com/9152238/75748026-7125da00-5d59-11ea-8b10-a26cac99aafd.jpg)

請模擬該工單的行為。

**Comment by ponyhsu** [comment]
已修正
