### ISSUE TITLE
Bug:NAS Path雙反斜線消失，變成單反斜線。

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#208]
![messageImage_1583215548237](https://user-images.githubusercontent.com/9152238/75747793-d0371f00-5d58-11ea-847f-84b7913c9447.jpg)

**Comment by Le1779** [comment]
fixed

**Comment by chanchengliang** [comment]
寄出的email有這個問題。

**Comment by Le1779** [comment]
fixed
