### ISSUE TITLE
Bug:只有一筆時，會出現紅色的比對不同的結果

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#217]
![2](https://user-images.githubusercontent.com/9152238/76923410-436e9280-690e-11ea-9efd-35eec9375c3c.png)
![3](https://user-images.githubusercontent.com/9152238/76923439-541f0880-690e-11ea-9afd-f3bd839c9a1b.png)

**Comment by zxc37880** [comment]
以調整樣式語顯示樣式邏輯。
