### ISSUE TITLE
新需求：quill的訊息輸入的部份加上字型的顏色設定(mantis 9019)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#220]
![2020-3-18 下午 01-46-58](https://user-images.githubusercontent.com/9152238/76929547-67869f80-691f-11ea-8a2e-f98097ba8bc0.png)

**Comment by chanchengliang** [comment]
這個部份建議製作新版本有HTML tag，在上正式站前，把目前FlowLog中的markdown訊息先轉成HTML TAG即可。

**Comment by chanchengliang** [comment]
1．Pony請製作一個GetLogImage(string guid), 此檔直接從工單專案中的./Image目錄中讀取圖檔回傳，請一樣用Memory Read方式製作。(guid ) + .jpg即是image的檔名. 

2.Bash64 image decoder:
https://stackoverflow.com/questions/5083336/decoding-base64-image
可轉成image存檔。

3．Kevin若有任何需要幫忙可請Pony協助。

**Comment by Le1779** [comment]
已完成，圖檔目前放在/FilesUpload/images中
![200319](https://user-images.githubusercontent.com/28716003/77058692-bd874000-6a10-11ea-990c-57cc1d42844b.PNG)

**Comment by chanchengliang** [comment]
![2020-4-9 上午 09-48-44](https://user-images.githubusercontent.com/9152238/78849607-86bcac80-7a47-11ea-96ff-711657f02a59.png)

git的記錄有HTML的tag在。(請移除)

**Comment by Le1779** [comment]
已修正
