### ISSUE TITLE
新需求：安裝Elmah套件

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#221]
1．請照「 ASP.NET mvc 王者歸來」 書中說明的方法，安裝套件。以方便捕捉系統的例外。
2．並在系統管理者頁面增加一下功能頁籤 ，指到該向該套件的頁面
3．該套件的頁面標準路徑，請要更改。
4．目前的log4.net的設定，為一個小時分成一個檔案，請改成以日為單位。

**Comment by Le1779** [comment]
已新增，log4net已調整
