### ISSUE TITLE
Bug:點選"工單形式"時，無反應

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#223]
![2020-4-1 上午 11-14-13](https://user-images.githubusercontent.com/9152238/78095717-3d96a800-740a-11ea-906b-b91e306eedc7.png)

**Comment by ponyhsu** [comment]
已修正
![image](https://user-images.githubusercontent.com/48582661/78620310-2c3e1780-78b2-11ea-8360-15371bab8bac.png)
