### ISSUE TITLE
UI:選擇人員的Dialog的行為修正

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#237]
(1) 選擇部門時, 直接轉入選擇部門的成員頁面。(原預設是自動選擇全部的成員，因為是機密工單，此情況不太可能產生，不需要自動選擇全部的成員)

(2) 若有選擇該部門成員時，則自動帶入該部門的leader。(防呆，若無部門主管的話，工單無法處理)

![2020-5-26 上午 09-51-50](https://user-images.githubusercontent.com/9152238/82852943-d7746000-9f36-11ea-985f-a8892659186f.png)

**Comment by Le1779** [comment]
已調整
