### ISSUE TITLE
UI:機密工單-可選擇的部門應與參與人員連動(防呆)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#240]
若是該部門沒有人參與，是否就Disable或是不出現為佳？
![2020-5-26 上午 10-11-05](https://user-images.githubusercontent.com/9152238/82853918-93cf2580-9f39-11ea-94a8-19fe2e974346.png)

**Comment by Le1779** [comment]
已調整

**Comment by chanchengliang** [comment]
非PM部門此功能已修正。但工單是被退到PM時，此功能無作用

**Comment by Le1779** [comment]
已修正
