### ISSUE TITLE
UI:機密工單上傳完後，申請的部門「欄位」和一般工單怎麼不同？

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#241]
![申請部門的值](https://user-images.githubusercontent.com/9152238/82855319-929ff780-9f3d-11ea-933f-a01ad1baf810.png)

**Comment by Le1779** [comment]
![image](https://user-images.githubusercontent.com/28716003/82968299-94ca8a80-9fff-11ea-8d4f-cb3f7f43c88f.png)
![image](https://user-images.githubusercontent.com/28716003/82968318-9dbb5c00-9fff-11ea-8728-4f1d6aa5d1fa.png)
