### ISSUE TITLE
UI:機密工單的log，文字為綠色不太明顯，建議選擇別的顏色

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#243]
![2020-5-26 上午 10-55-18](https://user-images.githubusercontent.com/9152238/82856055-a187a980-9f3f-11ea-832c-327f4d7d9ef0.png)

**Comment by Le1779** [comment]
已調整
![image](https://user-images.githubusercontent.com/28716003/82876246-10c6c300-9f6b-11ea-93ab-cdbd3ffe9f2d.png)
