### ISSUE TITLE
UI：機密工單的Button可以調整成和上面的一樣Style

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#244]
![2020-5-26 上午 11-02-48](https://user-images.githubusercontent.com/9152238/82856674-3212b980-9f41-11ea-88bd-e63210d7d2a9.png)

**Comment by Le1779** [comment]
已調整
![image](https://user-images.githubusercontent.com/28716003/82884173-f6dead80-9f75-11ea-8715-dca0a749bb27.png)
