### ISSUE TITLE
新需求：「進行中」頁面要能sort，紅框標示的欄位

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#252]
![2020-6-16 下午 03-22-39](https://user-images.githubusercontent.com/9152238/84744151-73990080-afe5-11ea-97f2-14d07c641d7e.png)

**Comment by Le1779** [comment]
已完成

**Comment by chanchengliang** [comment]
![2020-6-30 上午 10-19-52](https://user-images.githubusercontent.com/9152238/86076183-43a92d00-babc-11ea-8881-24675233494c.png)

**Comment by Le1779** [comment]
已調整
