### ISSUE TITLE
新需求：加上自訂搜尋區間

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#260]
1.統計區間可否指定開始/結尾區段
2.清單裏，除列"專案名稱"，請一併列出"客戶名稱"
3.click工單號碼時，可跳到工單內容

![2](https://user-images.githubusercontent.com/9152238/90207364-aa8a6780-de18-11ea-9b70-2e544766d901.png)

**Comment by Le1779** [comment]
已完成
