### ISSUE TITLE
新需求：已完成搜尋未和Excel報表連動

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#264]
1．搜尋完的結果，未和報告連動
2．建議直接把搜尋完的結果轉成json丟回後台，這樣後台就不用再用同條件去搜尋，得出結果

![2020-9-3 上午 11-09-24](https://user-images.githubusercontent.com/9152238/92067616-551df680-edd7-11ea-9fbb-e02aed20fefb.png)

**Comment by Le1779** [comment]
已完成，因為前端每次只會得到分頁過後的部分資料，所以還是需要把搜尋條件當作參數代入後端再搜尋一次。
