### ISSUE TITLE
Bug：git的下載功能失效

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#265]
網址如下：
http://192.168.255.17:8088/BonoboGitServer/Repository/0f8d8715-22d8-4ce0-a6c1-e37eb5b9fde8/8d6fd8943db5916bdfc5dc518072d9f6609d99ac/Tree2

![25](https://user-images.githubusercontent.com/9152238/92067900-0755be00-edd8-11ea-861f-be56118c08b5.png)

**Comment by Le1779** [comment]
已修正
