### ISSUE TITLE
Bug:NasPath的路徑比較功能的演算法有問題

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#271]
一樣的字的顏色用「黑色」表示。不同的用紅色
下圖，一樣的卻也是「紅色」的字。
![2020-9-10 下午 05-00-55](https://user-images.githubusercontent.com/9152238/92707133-a30e9d80-f387-11ea-9692-862949e53139.png)

**Comment by MartinWeng2020** [comment]
以上至測試站!!
