### ISSUE TITLE
Bug:在人工重啟單後「上一關 → 待處理」的狀態不會改變(#9568)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#278]
在人工轉單後「上一關 → 待處理」欄位的狀態就不會改變，會一直停留在轉單前的狀態。

問題發生工單:
WO-20200309-5DFC
WO-20190805-9F2A

![status01](https://user-images.githubusercontent.com/9152238/93972314-9be28900-fda4-11ea-8a8b-741f50e14d94.PNG)
![status02](https://user-images.githubusercontent.com/9152238/93972318-9d13b600-fda4-11ea-9811-7b99a27b7a5a.PNG)

**Comment by Le1779** [comment]
**已修正**
原因在於PM結案的時候最後一張的Task的`ActivityState`還是1

現在的做法:
- 選擇一個要復原的流程 (`ActivityState` 4 to 1)
- 選擇一個要完成的流程 (`ActivityState` 1 to 4)
