### ISSUE TITLE
PM->FD, FD退回。PM再次處理，送出後，不會送到FD

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#28]
![1](https://user-images.githubusercontent.com/9152238/54582477-ca630380-4a4b-11e9-9479-96175e1bb9a1.png)
![2](https://user-images.githubusercontent.com/9152238/54582478-cd5df400-4a4b-11e9-9914-cc56066ae35c.png)

**Comment by zxc37880** [comment]
Commit: [e5bbb20] 已修正。
