### ISSUE TITLE
簽核流程- 已完成頁分成上下半部

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#41]
上半部：
增加狀態欄：(未結案/已結案)

下半部為未結案區:
只有對 PM 提供按鈕及訊息，其它角色都不能按。
按下後，案件在流程狀態中->完成。(全部都結案)
此動作非常危險，必須要嚴正的提示使用者。

**Comment by Le1779** [comment]
已新增
