### ISSUE TITLE
結案/逾期通知

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#49]
結案或是即將逾期時，「未完成頁面」應該警示。逾期應該發信通知  該部門主管及專案經理。

**Comment by chanchengliang** [comment]
「 未結案列表」排列方式，以愈近結案日的愈上面。
「已經逾期」-外框 紅色+閃爍
「即將逾期」--三天內-外框紅色
「即將逾期」-七天內-外框黃色

**Comment by chanchengliang** [comment]
「已經逾期」-外框 紅色+閃爍
「即將逾期」--三天內-外框紅色
「即將逾期」-七天內-外框黃色

UI的表現方式，有更佳的表現方式，亦可。

**Comment by Le1779** [comment]
已調整
