### ISSUE TITLE
若建立工單時，選擇延伸自某工單

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#53]
在進入詳情時，找個地方放一下延申自某工單的該工單的超連結。
例如：工單WO-12，延伸自WO-11, 詳情頁面放一個WO-11的超連結。

**Comment by zxc37880** [comment]
Commit:  [98ad5fb]，以解決。

**Comment by chanchengliang** [comment]
![3333](https://user-images.githubusercontent.com/9152238/56111748-97992600-5f8b-11e9-941e-641e6fdb59f8.png)
