### ISSUE TITLE
已完頁面(新增查詢功能)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#61]
(1)可用查詢欄位:
工單號碼 / 客戶 / 專案名稱 / 結案 / 查時間的範圍(用建單日期) /姓名(下拉式選單，範單限定該部門)
用工單號的話則用WorkingOrderType來查
字型名稱 / Local File Name / codepage
(查詢條件為and)

(2)增加一個「下載查詢結果」
可以下載Excel檔

**Comment by zxc37880** [comment]
(1) 功能修正後完成。 Commit:  [0891048]
