### ISSUE TITLE
SPEC的修改機制

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/FontWorkOrder#99]
PM的上傳或是各單位的上傳，要能修改或刪除已經上傳的部份。(刪除需再次詢問)
UI分成上下兩區，上為暫存區
下為目前的最新的檔案區(依部門呈現)

**Comment by Le1779** [comment]
已新增

**Comment by chanchengliang** [comment]
原來的呈現方式(靠按鈕切換)，經DRG會議討論後，以上下呈現為佳。

**Comment by chanchengliang** [comment]
請將原來的[ 最新檔案」的切換的功能，移至「查看最新檔案」的按鈕功能

**Comment by chanchengliang** [comment]
檔案下載的功能請Boren協助。

**Comment by Le1779** [comment]
已完成
